title: Carmine Spagnuolo # name of the site
author: Carmine Spagnuolo  # name of site's author
email: spagnuolocarmine@gmail.com # email of site's author
url: https://spagnuolocarmine.github.io/ # root address of the site
description: > # description of the site (multiple lines allowed)
 my personal home page

permalink: /:slug.html

favicon: "./boat.png" # relative path to site's favicon
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
 - _pages